#pragma once
#include"Dx12Include.h"

namespace GR
{
	namespace Dx12
	{
		class SamplerState
		{
		public:
			static CD3DX12_STATIC_SAMPLER_DESC PointWrap(uint32_t registerIndex)
			{
				return CD3DX12_STATIC_SAMPLER_DESC(
					registerIndex,
					D3D12_FILTER_MIN_MAG_MIP_POINT,
					D3D12_TEXTURE_ADDRESS_MODE_WRAP,
					D3D12_TEXTURE_ADDRESS_MODE_WRAP,
					D3D12_TEXTURE_ADDRESS_MODE_WRAP);
			}

			static CD3DX12_STATIC_SAMPLER_DESC PointClamp(uint32_t registerIndex)
			{
				return CD3DX12_STATIC_SAMPLER_DESC(
					registerIndex,
					D3D12_FILTER_MIN_MAG_MIP_POINT,
					D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
					D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
					D3D12_TEXTURE_ADDRESS_MODE_CLAMP);
			}


			static CD3DX12_STATIC_SAMPLER_DESC LinearWrap(uint32_t registerIndex)
			{
				return CD3DX12_STATIC_SAMPLER_DESC(
					registerIndex,
					D3D12_FILTER_MIN_MAG_MIP_LINEAR,
					D3D12_TEXTURE_ADDRESS_MODE_WRAP,
					D3D12_TEXTURE_ADDRESS_MODE_WRAP,
					D3D12_TEXTURE_ADDRESS_MODE_WRAP);
			}

			static CD3DX12_STATIC_SAMPLER_DESC LinearClamp(uint32_t registerIndex)
			{
				return CD3DX12_STATIC_SAMPLER_DESC(
					registerIndex,
					D3D12_FILTER_MIN_MAG_MIP_LINEAR,
					D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
					D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
					D3D12_TEXTURE_ADDRESS_MODE_CLAMP);
			}

			static CD3DX12_STATIC_SAMPLER_DESC AnisotropicWrap(uint32_t registerIndex)
			{
				return CD3DX12_STATIC_SAMPLER_DESC(
					registerIndex,
					D3D12_FILTER_ANISOTROPIC,
					D3D12_TEXTURE_ADDRESS_MODE_WRAP,
					D3D12_TEXTURE_ADDRESS_MODE_WRAP,
					D3D12_TEXTURE_ADDRESS_MODE_WRAP);
			}

			static CD3DX12_STATIC_SAMPLER_DESC AnisotropicClamp(uint32_t registerIndex)
			{
				return CD3DX12_STATIC_SAMPLER_DESC(
					registerIndex,
					D3D12_FILTER_ANISOTROPIC,
					D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
					D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
					D3D12_TEXTURE_ADDRESS_MODE_CLAMP);
			}
		};
	}
}
