#pragma once
#include <Windows.h>
#include <iostream>
#include <vector>
#include <list>
#include <chrono>
#include <memory>
#include <ppl.h>
#include <ppltasks.h>
#include <map>
#include <queue>
#include <unordered_map>
#include <mutex>
#include <fstream>
#include <string>
#include <map>
#include <functional>
#include <algorithm>
#include <filesystem>
#include <atomic>
#include <chrono>
#include <ppl.h>
#include <filesystem>
#include <tuple>
#include <stack>
#include <tuple>
#include <shared_mutex>
#include <cassert>
namespace fs = std::filesystem;