#pragma once
#define SHADER_MACRO_DEFINE_MATERIAL_CODE    "__DEFINE_MATERIAL_CODE__"
#define SHADER_MACRO_DEFINE_MATERIAL_DATA    "__DEFINE_MATERIAL_DATA__"
#define SHADER_MACRO_DEFINE_SDSTATIC_OBJECT  "__SDSTATICOBJECT__"
#define SHADER_MACRO_DEFINE_SDSKINNED_OBJECT "__SDSKINNEDOBJECT__"
#define SHADER_MACRO_DEFINE_SDPAPER_OBJECT   "__SDPAPEROBJECT__"



#define SHADER_MACRO_DEFINE_RENDERER_MODE_3D    "__RENDERER_MODE_3D__"
#define SHADER_MACRO_DEFINE_RENDERER_MODE_PAPER "__RENDERER_MODE_PAPER__"
#define SHADER_MACRO_DEFINE_RENDERER_MODE_GUI   "__RENDERER_MODE_GUI__"


#define SHADER_NAME_SUFFIX_MATERIAL_DATA "_Data"
#define SHADER_NAME_SUFFIX_TEXTURE       "_Texture"





#define SHADER_CONSTANT_BUFFER_UNIT_SIZE 256